### ISSUE TITLE
returnCompleteBalances

### ISSUE THREAD

**Issue by mjagmalm** [anmatika/poloniex-api#2]
Hi

I really like this module. Would you mind adding "returnCompleteBalances" to the tradingApi?
It's as simple as adding the line
"returnCompleteBalances: () => makeRequest('returnCompleteBalances', {})," in the return clause of tradingApi.js

BR
Mats

**Comment by anmatika** [comment]
Hi Mats,

It's now added.

**Comment by matsjagmalm** [comment]
Great, thanks a lot!
