### ISSUE TITLE
Error when buying

### ISSUE THREAD

**Issue by lukasz-kaniowski** [anmatika/poloniex-api#3]
I'm getting ` body: '{"error":"Total must be at least 0.0001."}' }` error every time when I'm trying to buy. here is the code snippet 
``` js
tradingApi.buy('BTC_DGB', 130, 0.000005).then(console.log).catch(console.log)
```

I've tested the same amount with https://github.com/premasagar/poloniex.js and it works fine. 

Any ideas?

**Comment by anmatika** [comment]
Hi, buy method parameter is an object, please call it as below:

````
tradingApi.buy({
    currencyPair: 'BTC_DGB',
    amount: 130,
    rate: 0.000005
  }).then(msg => console.log(msg.body))
    .catch(err => console.log(err))
````

I updated the readme accordingly.

**Comment by lukasz-kaniowski** [comment]
sure it is, I'm blind sometimes. thanks for reply.

**Comment by anmatika** [comment]
it's okay, thanks.
