### ISSUE TITLE
Support for "fillOrKill", "immediateOrCancel", "postOnly" for buy api call

### ISSUE THREAD

**Issue by lukasz-kaniowski** [anmatika/poloniex-api#5]
Would be great to add support for those additional parameters.

**Comment by anmatika** [comment]
Hi, just noticed this issue, I'll add these today or latest tomorrow. 
If you want to, you also can create a pull request for those.

**Comment by anmatika** [comment]
Okay, it was easy change after all so I pushed the changes into new branch https://github.com/anmatika/poloniex-api/tree/add_optional_buy_params

Planning to merge the changes into master in the evening once I get the change tested.

**Comment by anmatika** [comment]
Optional parameters for buy api call now added.

**Comment by lukasz-kaniowski** [comment]
@anmatika Thanks a lot
